'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")>  _
    Partial Friend NotInheritable Class ChungJee
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As ChungJee = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ChungJee()),ChungJee)
        
        Public Shared ReadOnly Property [Default]() As ChungJee
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://120.211.170.8:5000")>  _
        Public Property strNasHostName() As String
            Get
                Return CType(Me("strNasHostName"),String)
            End Get
            Set
                Me("strNasHostName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("zhanglj")>  _
        Public Property strNasUserName() As String
            Get
                Return CType(Me("strNasUserName"),String)
            End Get
            Set
                Me("strNasUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strNasPassWord() As String
            Get
                Return CType(Me("strNasPassWord"),String)
            End Get
            Set
                Me("strNasPassWord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("基础数据")>  _
        Public Property con_BASE_DATA() As String
            Get
                Return CType(Me("con_BASE_DATA"),String)
            End Get
            Set
                Me("con_BASE_DATA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strNasSid() As String
            Get
                Return CType(Me("strNasSid"),String)
            End Get
            Set
                Me("strNasSid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("单位信息表")>  _
        Public Property con_COMPANY_INFO() As String
            Get
                Return CType(Me("con_COMPANY_INFO"),String)
            End Get
            Set
                Me("con_COMPANY_INFO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/home/")>  _
        Public Property con_NAS_HOME_FOLDERNAME() As String
            Get
                Return CType(Me("con_NAS_HOME_FOLDERNAME"),String)
            End Get
            Set
                Me("con_NAS_HOME_FOLDERNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("开始日期：")>  _
        Public Property con_START_DATE() As String
            Get
                Return CType(Me("con_START_DATE"),String)
            End Get
            Set
                Me("con_START_DATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("结束日期：")>  _
        Public Property con_END_DATE() As String
            Get
                Return CType(Me("con_END_DATE"),String)
            End Get
            Set
                Me("con_END_DATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("数据聚合")>  _
        Public Property strTabName() As String
            Get
                Return CType(Me("strTabName"),String)
            End Get
            Set
                Me("strTabName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{""data"":[{""url"":""https://e.dianping.com/couponrecord/queryCouponRecordDetails""},{"& _ 
            """url"":""https://e.dianping.com/couponrecord/consumeItemsNewDownload""},{""url"":""htt"& _ 
            "ps://e.dianping.com/smartBill/download/downloadLink""}]}")>  _
        Public Property jsonUrlList() As String
            Get
                Return CType(Me("jsonUrlList"),String)
            End Get
            Set
                Me("jsonUrlList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://e.dianping.com/")>  _
        Public Property strHomePage() As String
            Get
                Return CType(Me("strHomePage"),String)
            End Get
            Set
                Me("strHomePage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{""data"":[{""url"":""https://e.dianping.com/couponrecord/queryCouponRecordDetails"",""b"& _ 
            "tnForward"":""document.getElementsByTagName('iframe')[0].contentDocument.getElemen"& _ 
            "tsByClassName('anticon anticon-left')[1].click()"",""btnBackward"":""document.getEle"& _ 
            "mentsByTagName('iframe')[0].contentDocument.getElementsByClassName('anticon anti"& _ 
            "con-right')[1].click()"",""lbPage"":""document.getElementsByTagName('iframe')[0].con"& _ 
            "tentDocument.getElementsByClassName('ant-pagination-total-text')[0].innerText""}]"& _ 
            "}")>  _
        Public Property btnBottomScript() As String
            Get
                Return CType(Me("btnBottomScript"),String)
            End Get
            Set
                Me("btnBottomScript") = value
            End Set
        End Property
    End Class
End Namespace
